version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: cerberus-vault-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cerberus_vault
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
